### ISSUE TITLE
Update Commentator.OrchardCore

### ISSUE THREAD

**Issue by Line4GitHub** [jsalgado10/Commentator.OrchardCore#10]
Can you tell me when you will update Commentator.OrchardCore to Orchard Core 1.0.0-rc2-15949 ~ 16238 ?
Thank you very much!

**Comment by Line4GitHub** [comment]
Thank you very much! for your quick reply.
------
From Orchard Core 1.0.0-rc2-15949,
https://github.com/OrchardSkills/OrchardSkills.OrchardCore.Commentator
The CommentatorPart does not work!

**Comment by jsalgado10** [comment]
I am currently working on updating the Plugin to use Orchard Core 1.0.0 now that it has been released

**Comment by jsalgado10** [comment]
you can download Commentator.OrchardCore 1.2.0-rc-1 nuget package. This version is using Orchard Core 1.0.0. You can also checkout the dev branch
