### ISSUE TITLE
The CommentatorPart does not work

### ISSUE THREAD

**Issue by fenngineering** [jsalgado10/Commentator.OrchardCore#8]
Hello,

I am trying to integrate with the CommentatorPart but I am struggling to get it working on my site.

I am using the latest RC2 branch of OrchardCore and I have got the latest Commentator.OrchardCore dependency added to mu solution.

When I get into the Admin features I do see the module added, so I enabled this. 
![image](https://user-images.githubusercontent.com/35530714/107408283-abb7fb00-6b02-11eb-814f-58bae610ac1e.png)

I have also set the Security\Roles sections for Anonymous 
![image](https://user-images.githubusercontent.com/35530714/107408198-8cb96900-6b02-11eb-853d-fe49dfe8af7f.png)

I was expecting that the CommentatorPart would be visible in the Content Definition\Content Parts in the Contents section however it isn't, when I try to "Create a New Part" with the CommentatorPart as a name, I get this error:-
![image](https://user-images.githubusercontent.com/35530714/107408732-40225d80-6b03-11eb-8f66-419974e60cb4.png)

I would have expected to see the CommentatorPart in this "Add Part" section of my "Article", As you can see is is not available
![image](https://user-images.githubusercontent.com/35530714/107409124-b9ba4b80-6b03-11eb-91b3-3f682e95fe35.png)

Please could you give me some advice on why this may not be working?

This is my github repo [https://github.com/fenngineering/FennasPrem](https://github.com/fenngineering/FennasPrem)

My sites are is a SaaS site and a tenant using the Blog recipe.

[](url)

Kind regards
Andy

**Comment by jsalgado10** [comment]
I setup a new tenant using your code and the blog them and I can see the commentator part. Can you try setting up a new tenant and enable the commentator module, then see if you are able to see the commentator part?

Thanks

**Comment by jsalgado10** [comment]
One more thing, make sure that the commentator part is flag as attachable, otherwise the content part will not show up on the list

![image](https://user-images.githubusercontent.com/16822143/107462241-4aebeb00-6b21-11eb-842e-cea022317577.png)

**Comment by fenngineering** [comment]
@jsalgado10 Thanks for speedy reply, that actually worked from a reinstallation of the SaaS and Tenant, I can now see the comments section - Brilliant.

One question that I have, is how do you add this feature to an already established site(s) I suspect there's got to be an "Update" the database to include this new Part, or can this be done from the code base?

Kind regards

**Comment by jsalgado10** [comment]
@fenngineering  when you enable the commentator feature, it will add the commentator part and comment Post content type . you will need to add the commentator part manually to your own content type. I am using a migration script to add the new part and content type to your tenant. 

Check out the commentator.recipe.json file under the Migration folder.

**Comment by fenngineering** [comment]
Please close this issue as I managed to merge the commentator.recipe.json  with my live ContentDefinition.json for the tenant and it work as above.

Thanks for your help

**Comment by jsalgado10** [comment]
No problem.

Also keep in mind that starting with NuGet package version 1.0.8, I am using Orchard Core 1.0.0-rc2-15787.

**Comment by fenngineering** [comment]
Will you be adding moderating features as some point like an approval\rejection etc?

**Comment by jsalgado10** [comment]
Yes I have added a new Issue #9 for this request

**Comment by Line4GitHub** [comment]
Can you tell me when you will update Commentator.OrchardCore to Orchard Core 1.0.0-rc2-15948 ~ 16238 ?
Thank you very much!
